project_id = "pjnyuexzxhwnsogxweng"

[functions.generate-article]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.process-scheduled-posts]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false
